/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://56ozxddmofftja4cexuv5i7mkm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-os66zsvbizagzcpi7x6zwsnsnm",
    "aws_cognito_identity_pool_id": "us-east-1:2a9c0c79-c815-49a4-b169-97ecbcbc4cfc",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_EztlksTJO",
    "aws_user_pools_web_client_id": "48jsei3s3n754vk8drpfh4tomf",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
